function [linie, farbe] = erstelle_linieneigenschaften_V001(liniennummer)
% ERSTELLE_LINIENEIGENSCHAFTEN_V001 
% Gibt individuelle Linieneigenschaften zurück, damit die Daten
% unterscheidbar sind.

% https://de.mathworks.com/help/matlab/ref/linespec.html
linienarten = [ "-s"; ...
                "-.o"; ...
                ":x"; ...
                "--*"; ...
                ":^"; ...
                "--v"; ...
                "-.d"; ...
                "--+"];

% http://math.loyola.edu/~loberbro/matlab/html/colorsInMatlab.html
farben = [      [0,         0.4470,     0.7410]; ...
                [0.8500,    0.3250,     0.0980]; ...
                [0.9290,    0.6940,     0.1250]; ...
                [0.4940,    0.1840,     0.5560]; ...
                [0.4660,    0.6740,     0.1880]; ...
                [0.3010,    0.7450,     0.9330]; ...
                [0.6350,    0.0780,     0.1840]; ...
                [0,         0,          1]; ...
                [0,         0.5,        0]; ...
                [0.25,      0.25,       0.25]; ...
                [0.75,      0,          0.75]];
            
anzahl_linienarten = length(linienarten);
anzahl_farben = length(farben(:,1));

if liniennummer > (anzahl_linienarten * anzahl_farben)
    linie = '-+';
    farbe = [1 0 0];
    disp('Farben in Linieneigenschaften müssen erweitert werden!');
    return;
end

linie = linienarten(fix(liniennummer / anzahl_farben) + 1);
if (mod(liniennummer, anzahl_farben) > 0)
    farbe = farben(mod(liniennummer, anzahl_farben), :);
else
    farbe = farben(anzahl_farben, :);
end

end

